### ISSUE TITLE
There's an issue configuring the SoftLayer connector.

### ISSUE THREAD

**Issue by bassemelkhansa** [slipstream/SlipStreamWafflePlanning#6]
Saving after each attribute insertion results in losing the value after page reload.

Details: After successfully installing the connector, and when trying to configure it by giving values to different attributes ("image-id-for-orchestrator" "flavor" "tarball-pointing-to-ss-client" ) and after saving successfully, and when refreshing the page to see if the 'save' took effect, all entered values disappear, meaning that the successful 'save' was a 'fake' one! the only way to make it work(saved and still be there after a page reload) is actually to insert values for all required fields and save all at once.

**Comment by bassemelkhansa** [comment]
issue is not persistent.

**Comment by loomis** [comment]
Reopen on connector repository if still relevant.
